AllCops:
  TargetRubyVersion: 2.4

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/FirstParameterIndentation:
  EnforcedStyle: consistent

Layout/IndentArray:
  EnforcedStyle: consistent

Layout/IndentHash:
  EnforcedStyle: consistent

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/NumericPredicate:
  Enabled: False
  # EnforcedStyle: comparison

# rubocop 0.43 does not accept foo_bar0 or foo_bar_0.
Naming/VariableNumber:
  Enabled: False

# Sometimes we want to write non-warnings to stderr when piping.
Style/StderrPuts:
  Enabled: False

Style/Documentation:
  Exclude:
    - 'test/**/*'

Metrics/AbcSize:
  Max: 30
  Exclude:
    - 'bin/*'
    - 'test/**/*'

Metrics/CyclomaticComplexity:
  Max: 15
  Exclude:
    - 'test/**/*'

Metrics/PerceivedComplexity:
  Max: 15
  Exclude:
    - 'test/**/*'

Metrics/ParameterLists:
  Max: 10

Metrics/MethodLength:
  Max: 25
  Exclude:
    - 'bin/*'
    - 'test/**/*'

Metrics/BlockLength:
  Max: 30
  Exclude:
    - 'bin/*'
    - 'test/**/*'

Metrics/ClassLength:
  Max: 1000

Metrics/ModuleLength:
  Max: 1000
